//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPro.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSBResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSBResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealerPro.Config.CSBResources", typeof(CSBResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vs5l7Gex7kf4iddwCeA51KYZ6Vr592NX5B19p7R8PVK2n0VKogMdBg==.
        /// </summary>
        internal static string ASxFunctionKey {
            get {
                return ResourceManager.GetString("ASxFunctionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=servicebookingdbservtest.database.windows.net;Initial Catalog=ServiceBookingDb;User ID=ExperiecoAdmin;Password=9aJrtENEU6JV3h$.
        /// </summary>
        internal static string DBConnectionString {
            get {
                return ResourceManager.GetString("DBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el5FYLxGa0mcINp0J/pyAMwMwy3qgiqlntSG9zYa2umJTmgrZkapqA==.
        /// </summary>
        internal static string DCxFunctionKey {
            get {
                return ResourceManager.GetString("DCxFunctionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string DealerId {
            get {
                return ResourceManager.GetString("DealerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\ExcelData\TestDataDealerPro.xlsx.
        /// </summary>
        internal static string ExcelPath {
            get {
                return ResourceManager.GetString("ExcelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\TestReports\JSONRequest\.
        /// </summary>
        internal static string JSonRequestPath {
            get {
                return ResourceManager.GetString("JSonRequestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\TestReports\JSONResponse\.
        /// </summary>
        internal static string JSonResponsePath {
            get {
                return ResourceManager.GetString("JSonResponsePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\TestReports\CarBookingServiceReport.html.
        /// </summary>
        internal static string ReportPath {
            get {
                return ResourceManager.GetString("ReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\Config\XMLFile.xml.
        /// </summary>
        internal static string ReportXMLPath {
            get {
                return ResourceManager.GetString("ReportXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Preety.Sehrawat\Desktop\Automation-CarServiceBooking\DealerPro\DealerPro\Screenshots\.
        /// </summary>
        internal static string ScreenShotPath {
            get {
                return ResourceManager.GetString("ScreenShotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0HJoLK5CYR3blISJDrMmYwi2auczEwya8FnwFVJnVWvbWnpEPDa13g==.
        /// </summary>
        internal static string SCVxFunctionKey {
            get {
                return ResourceManager.GetString("SCVxFunctionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dv0lLatl43G0/4rcCyFlKrj/uzDeW87qZWgaKTtCRbhhAzA7Q3bG3Q==.
        /// </summary>
        internal static string VMxFunctionKey {
            get {
                return ResourceManager.GetString("VMxFunctionKey", resourceCulture);
            }
        }
    }
}
